<?php

$list = '{
	"AF":{"iso":"AF","name":"Afghanistan","visited":false},
	"AL":{"iso":"AL","name":"Albania","visited":false},
	"DZ":{"iso":"DZ","name":"Algeria","visited":false},
	"AS":{"iso":"AS","name":"American Samoa","visited":false},
	"AD":{"iso":"AD","name":"Andorra","visited":false},
	"AO":{"iso":"AO","name":"Angola","visited":false},
	"AI":{"iso":"AI","name":"Anguilla","visited":false},
	"AQ":{"iso":"AQ","name":"Antarctica","visited":false},
	"AG":{"iso":"AG","name":"Antigua and Barbuda","visited":false},
	"AR":{"iso":"AR","name":"Argentina","visited":false},
	"AM":{"iso":"AM","name":"Armenia","visited":false},
	"AW":{"iso":"AW","name":"Aruba","visited":false},
	"AU":{"iso":"AU","name":"Australia","visited":false},
	"AT":{"iso":"AT","name":"Austria","visited":false},
	"AZ":{"iso":"AZ","name":"Azerbaijan","visited":false},
	"BS":{"iso":"BS","name":"Bahamas","visited":false},
	"BH":{"iso":"BH","name":"Bahrain","visited":false},
	"BD":{"iso":"BD","name":"Bangladesh","visited":false},
	"BB":{"iso":"BB","name":"Barbados","visited":false},
	"BY":{"iso":"BY","name":"Belarus","visited":false},
	"BE":{"iso":"BE","name":"Belgium","visited":false},
	"BZ":{"iso":"BZ","name":"Belize","visited":false},
	"BJ":{"iso":"BJ","name":"Benin","visited":false},
	"BM":{"iso":"BM","name":"Bermuda","visited":false},
	"BT":{"iso":"BT","name":"Bhutan","visited":false},
	"BO":{"iso":"BO","name":"Bolivia","visited":false},
	"BA":{"iso":"BA","name":"Bosnia and Herzegovina","visited":false},
	"BW":{"iso":"BW","name":"Botswana","visited":false},
	"BV":{"iso":"BV","name":"Bouvet Island","visited":false},
	"BR":{"iso":"BR","name":"Brazil","visited":false},
	"BQ":{"iso":"BQ","name":"British Antarctic Territory","visited":false},
	"IO":{"iso":"IO","name":"British Indian Ocean Territory","visited":false},
	"VG":{"iso":"VG","name":"British Virgin Islands","visited":false},
	"BN":{"iso":"BN","name":"Brunei","visited":false},
	"BG":{"iso":"BG","name":"Bulgaria","visited":false},
	"BF":{"iso":"BF","name":"Burkina Faso","visited":false},
	"BI":{"iso":"BI","name":"Burundi","visited":false},
	"KH":{"iso":"KH","name":"Cambodia","visited":false},
	"CM":{"iso":"CM","name":"Cameroon","visited":false},
	"CA":{"iso":"CA","name":"Canada","visited":false},
	"CT":{"iso":"CT","name":"Canton and Enderbury Islands","visited":false},
	"CV":{"iso":"CV","name":"Cape Verde","visited":false},
	"KY":{"iso":"KY","name":"Cayman Islands","visited":false},
	"CF":{"iso":"CF","name":"Central African Republic","visited":false},
	"TD":{"iso":"TD","name":"Chad","visited":false},
	"CL":{"iso":"CL","name":"Chile","visited":false},
	"CN":{"iso":"CN","name":"China","visited":false},
	"CX":{"iso":"CX","name":"Christmas Island","visited":false},
	"CC":{"iso":"CC","name":"Cocos [Keeling] Islands","visited":false},
	"CO":{"iso":"CO","name":"Colombia","visited":false},
	"KM":{"iso":"KM","name":"Comoros","visited":false},
	"CG":{"iso":"CG","name":"Congo - Brazzaville","visited":false},
	"CD":{"iso":"CD","name":"Congo - Kinshasa","visited":false},
	"CK":{"iso":"CK","name":"Cook Islands","visited":false},
	"CR":{"iso":"CR","name":"Costa Rica","visited":false},
	"HR":{"iso":"HR","name":"Croatia","visited":false},
	"CU":{"iso":"CU","name":"Cuba","visited":false},
	"CY":{"iso":"CY","name":"Cyprus","visited":false},
	"CZ":{"iso":"CZ","name":"Czech Republic","visited":false},
	"CI":{"iso":"CI","name":"Côte d’Ivoire","visited":false},
	"DK":{"iso":"DK","name":"Denmark","visited":false},
	"DJ":{"iso":"DJ","name":"Djibouti","visited":false},
	"DM":{"iso":"DM","name":"Dominica","visited":false},
	"DO":{"iso":"DO","name":"Dominican Republic","visited":false},
	"NQ":{"iso":"NQ","name":"Dronning Maud Land","visited":false},
	"DD":{"iso":"DD","name":"East Germany","visited":false},
	"EC":{"iso":"EC","name":"Ecuador","visited":false},
	"EG":{"iso":"EG","name":"Egypt","visited":false},
	"SV":{"iso":"SV","name":"El Salvador","visited":false},
	"GQ":{"iso":"GQ","name":"Equatorial Guinea","visited":false},
	"ER":{"iso":"ER","name":"Eritrea","visited":false},
	"EE":{"iso":"EE","name":"Estonia","visited":false},
	"ET":{"iso":"ET","name":"Ethiopia","visited":false},
	"FK":{"iso":"FK","name":"Falkland Islands","visited":false},
	"FO":{"iso":"FO","name":"Faroe Islands","visited":false},
	"FJ":{"iso":"FJ","name":"Fiji","visited":false},
	"FI":{"iso":"FI","name":"Finland","visited":false},
	"FR":{"iso":"FR","name":"France","visited":false},
	"GF":{"iso":"GF","name":"French Guiana","visited":false},
	"PF":{"iso":"PF","name":"French Polynesia","visited":false},
	"TF":{"iso":"TF","name":"French Southern Territories","visited":false},
	"FQ":{"iso":"FQ","name":"French Southern and Antarctic Territories","visited":false},
	"GA":{"iso":"GA","name":"Gabon","visited":false},
	"GM":{"iso":"GM","name":"Gambia","visited":false},
	"GE":{"iso":"GE","name":"Georgia","visited":false},
	"DE":{"iso":"DE","name":"Germany","visited":false},
	"GH":{"iso":"GH","name":"Ghana","visited":false},
	"GI":{"iso":"GI","name":"Gibraltar","visited":false},
	"GR":{"iso":"GR","name":"Greece","visited":false},
	"GL":{"iso":"GL","name":"Greenland","visited":false},
	"GD":{"iso":"GD","name":"Grenada","visited":false},
	"GP":{"iso":"GP","name":"Guadeloupe","visited":false},
	"GU":{"iso":"GU","name":"Guam","visited":false},
	"GT":{"iso":"GT","name":"Guatemala","visited":false},
	"GG":{"iso":"GG","name":"Guernsey","visited":false},
	"GN":{"iso":"GN","name":"Guinea","visited":false},
	"GW":{"iso":"GW","name":"Guinea-Bissau","visited":false},
	"GY":{"iso":"GY","name":"Guyana","visited":false},
	"HT":{"iso":"HT","name":"Haiti","visited":false},
	"HM":{"iso":"HM","name":"Heard Island and McDonald Islands","visited":false},
	"HN":{"iso":"HN","name":"Honduras","visited":false},
	"HK":{"iso":"HK","name":"Hong Kong SAR China","visited":false},
	"HU":{"iso":"HU","name":"Hungary","visited":false},
	"IS":{"iso":"IS","name":"Iceland","visited":false},
	"IN":{"iso":"IN","name":"India","visited":false},
	"ID":{"iso":"ID","name":"Indonesia","visited":false},
	"IR":{"iso":"IR","name":"Iran","visited":false},
	"IQ":{"iso":"IQ","name":"Iraq","visited":false},
	"IE":{"iso":"IE","name":"Ireland","visited":false},
	"IM":{"iso":"IM","name":"Isle of Man","visited":false},
	"IL":{"iso":"IL","name":"Israel","visited":false},
	"IT":{"iso":"IT","name":"Italy","visited":false},
	"JM":{"iso":"JM","name":"Jamaica","visited":false},
	"JP":{"iso":"JP","name":"Japan","visited":false},
	"JE":{"iso":"JE","name":"Jersey","visited":false},
	"JT":{"iso":"JT","name":"Johnston Island","visited":false},
	"JO":{"iso":"JO","name":"Jordan","visited":false},
	"KZ":{"iso":"KZ","name":"Kazakhstan","visited":false},
	"KE":{"iso":"KE","name":"Kenya","visited":false},
	"KI":{"iso":"KI","name":"Kiribati","visited":false},
	"KW":{"iso":"KW","name":"Kuwait","visited":false},
	"KG":{"iso":"KG","name":"Kyrgyzstan","visited":false},
	"LA":{"iso":"LA","name":"Laos","visited":false},
	"LV":{"iso":"LV","name":"Latvia","visited":false},
	"LB":{"iso":"LB","name":"Lebanon","visited":false},
	"LS":{"iso":"LS","name":"Lesotho","visited":false},
	"LR":{"iso":"LR","name":"Liberia","visited":false},
	"LY":{"iso":"LY","name":"Libya","visited":false},
	"LI":{"iso":"LI","name":"Liechtenstein","visited":false},
	"LT":{"iso":"LT","name":"Lithuania","visited":false},
	"LU":{"iso":"LU","name":"Luxembourg","visited":false},
	"MO":{"iso":"MO","name":"Macau SAR China","visited":false},
	"MK":{"iso":"MK","name":"Macedonia","visited":false},
	"MG":{"iso":"MG","name":"Madagascar","visited":false},
	"MW":{"iso":"MW","name":"Malawi","visited":false},
	"MY":{"iso":"MY","name":"Malaysia","visited":false},
	"MV":{"iso":"MV","name":"Maldives","visited":false},
	"ML":{"iso":"ML","name":"Mali","visited":false},
	"MT":{"iso":"MT","name":"Malta","visited":false},
	"MH":{"iso":"MH","name":"Marshall Islands","visited":false},
	"MQ":{"iso":"MQ","name":"Martinique","visited":false},
	"MR":{"iso":"MR","name":"Mauritania","visited":false},
	"MU":{"iso":"MU","name":"Mauritius","visited":false},
	"YT":{"iso":"YT","name":"Mayotte","visited":false},
	"FX":{"iso":"FX","name":"Metropolitan France","visited":false},
	"MX":{"iso":"MX","name":"Mexico","visited":false},
	"FM":{"iso":"FM","name":"Micronesia","visited":false},
	"MI":{"iso":"MI","name":"Midway Islands","visited":false},
	"MD":{"iso":"MD","name":"Moldova","visited":false},
	"MC":{"iso":"MC","name":"Monaco","visited":false},
	"MN":{"iso":"MN","name":"Mongolia","visited":false},
	"ME":{"iso":"ME","name":"Montenegro","visited":false},
	"MS":{"iso":"MS","name":"Montserrat","visited":false},
	"MA":{"iso":"MA","name":"Morocco","visited":false},
	"MZ":{"iso":"MZ","name":"Mozambique","visited":false},
	"MM":{"iso":"MM","name":"Myanmar [Burma]","visited":false},
	"NA":{"iso":"NA","name":"Namibia","visited":false},
	"NR":{"iso":"NR","name":"Nauru","visited":false},
	"NP":{"iso":"NP","name":"Nepal","visited":false},
	"NL":{"iso":"NL","name":"Netherlands","visited":false},
	"AN":{"iso":"AN","name":"Netherlands Antilles","visited":false},
	"NT":{"iso":"NT","name":"Neutral Zone","visited":false},
	"NC":{"iso":"NC","name":"New Caledonia","visited":false},
	"NZ":{"iso":"NZ","name":"New Zealand","visited":false},
	"NI":{"iso":"NI","name":"Nicaragua","visited":false},
	"NE":{"iso":"NE","name":"Niger","visited":false},
	"NG":{"iso":"NG","name":"Nigeria","visited":false},
	"NU":{"iso":"NU","name":"Niue","visited":false},
	"NF":{"iso":"NF","name":"Norfolk Island","visited":false},
	"KP":{"iso":"KP","name":"North Korea","visited":false},
	"VD":{"iso":"VD","name":"North Vietnam","visited":false},
	"MP":{"iso":"MP","name":"Northern Mariana Islands","visited":false},
	"NO":{"iso":"NO","name":"Norway","visited":false},
	"OM":{"iso":"OM","name":"Oman","visited":false},
	"PC":{"iso":"PC","name":"Pacific Islands Trust Territory","visited":false},
	"PK":{"iso":"PK","name":"Pakistan","visited":false},
	"PW":{"iso":"PW","name":"Palau","visited":false},
	"PS":{"iso":"PS","name":"Palestinian Territories","visited":false},
	"PA":{"iso":"PA","name":"Panama","visited":false},
	"PZ":{"iso":"PZ","name":"Panama Canal Zone","visited":false},
	"PG":{"iso":"PG","name":"Papua New Guinea","visited":false},
	"PY":{"iso":"PY","name":"Paraguay","visited":false},
	"YD":{"iso":"YD","name":"People\'s Democratic Republic of Yemen","visited":false},
	"PE":{"iso":"PE","name":"Peru","visited":false},
	"PH":{"iso":"PH","name":"Philippines","visited":false},
	"PN":{"iso":"PN","name":"Pitcairn Islands","visited":false},
	"PL":{"iso":"PL","name":"Poland","visited":false},
	"PT":{"iso":"PT","name":"Portugal","visited":false},
	"PR":{"iso":"PR","name":"Puerto Rico","visited":false},
	"QA":{"iso":"QA","name":"Qatar","visited":false},
	"RO":{"iso":"RO","name":"Romania","visited":false},
	"RU":{"iso":"RU","name":"Russia","visited":false},
	"RW":{"iso":"RW","name":"Rwanda","visited":false},
	"RE":{"iso":"RE","name":"Réunion","visited":false},
	"BL":{"iso":"BL","name":"Saint Barthélemy","visited":false},
	"SH":{"iso":"SH","name":"Saint Helena","visited":false},
	"KN":{"iso":"KN","name":"Saint Kitts and Nevis","visited":false},
	"LC":{"iso":"LC","name":"Saint Lucia","visited":false},
	"MF":{"iso":"MF","name":"Saint Martin","visited":false},
	"PM":{"iso":"PM","name":"Saint Pierre and Miquelon","visited":false},
	"VC":{"iso":"VC","name":"Saint Vincent and the Grenadines","visited":false},
	"WS":{"iso":"WS","name":"Samoa","visited":false},
	"SM":{"iso":"SM","name":"San Marino","visited":false},
	"SA":{"iso":"SA","name":"Saudi Arabia","visited":false},
	"SN":{"iso":"SN","name":"Senegal","visited":false},
	"RS":{"iso":"RS","name":"Serbia","visited":false},
	"CS":{"iso":"CS","name":"Serbia and Montenegro","visited":false},
	"SC":{"iso":"SC","name":"Seychelles","visited":false},
	"SL":{"iso":"SL","name":"Sierra Leone","visited":false},
	"SG":{"iso":"SG","name":"Singapore","visited":false},
	"SK":{"iso":"SK","name":"Slovakia","visited":false},
	"SI":{"iso":"SI","name":"Slovenia","visited":false},
	"SB":{"iso":"SB","name":"Solomon Islands","visited":false},
	"SO":{"iso":"SO","name":"Somalia","visited":false},
	"ZA":{"iso":"ZA","name":"South Africa","visited":false},
	"GS":{"iso":"GS","name":"South Georgia and the South Sandwich Islands","visited":false},
	"KR":{"iso":"KR","name":"South Korea","visited":false},
	"ES":{"iso":"ES","name":"Spain","visited":false},
	"LK":{"iso":"LK","name":"Sri Lanka","visited":false},
	"SD":{"iso":"SD","name":"Sudan","visited":false},
	"SR":{"iso":"SR","name":"Suriname","visited":false},
	"SJ":{"iso":"SJ","name":"Svalbard and Jan Mayen","visited":false},
	"SZ":{"iso":"SZ","name":"Swaziland","visited":false},
	"SE":{"iso":"SE","name":"Sweden","visited":false},
	"CH":{"iso":"CH","name":"Switzerland","visited":false},
	"SY":{"iso":"SY","name":"Syria","visited":false},
	"ST":{"iso":"ST","name":"São Tomé and Príncipe","visited":false},
	"TW":{"iso":"TW","name":"Taiwan","visited":false},
	"TJ":{"iso":"TJ","name":"Tajikistan","visited":false},
	"TZ":{"iso":"TZ","name":"Tanzania","visited":false},
	"TH":{"iso":"TH","name":"Thailand","visited":false},
	"TL":{"iso":"TL","name":"Timor-Leste","visited":false},
	"TG":{"iso":"TG","name":"Togo","visited":false},
	"TK":{"iso":"TK","name":"Tokelau","visited":false},
	"TO":{"iso":"TO","name":"Tonga","visited":false},
	"TT":{"iso":"TT","name":"Trinidad and Tobago","visited":false},
	"TN":{"iso":"TN","name":"Tunisia","visited":false},
	"TR":{"iso":"TR","name":"Turkey","visited":false},
	"TM":{"iso":"TM","name":"Turkmenistan","visited":false},
	"TC":{"iso":"TC","name":"Turks and Caicos Islands","visited":false},
	"TV":{"iso":"TV","name":"Tuvalu","visited":false},
	"UM":{"iso":"UM","name":"U.S. Minor Outlying Islands","visited":false},
	"PU":{"iso":"PU","name":"U.S. Miscellaneous Pacific Islands","visited":false},
	"VI":{"iso":"VI","name":"U.S. Virgin Islands","visited":false},
	"UG":{"iso":"UG","name":"Uganda","visited":false},
	"UA":{"iso":"UA","name":"Ukraine","visited":false},
	"SU":{"iso":"SU","name":"Union of Soviet Socialist Republics","visited":false},
	"AE":{"iso":"AE","name":"United Arab Emirates","visited":false},
	"GB":{"iso":"GB","name":"United Kingdom","visited":false},
	"US":{"iso":"US","name":"United States","visited":false},
	"ZZ":{"iso":"ZZ","name":"Unknown or Invalid Region","visited":false},
	"UY":{"iso":"UY","name":"Uruguay","visited":false},
	"UZ":{"iso":"UZ","name":"Uzbekistan","visited":false},
	"VU":{"iso":"VU","name":"Vanuatu","visited":false},
	"VA":{"iso":"VA","name":"Vatican City","visited":false},
	"VE":{"iso":"VE","name":"Venezuela","visited":false},
	"VN":{"iso":"VN","name":"Vietnam","visited":false},
	"WK":{"iso":"WK","name":"Wake Island","visited":false},
	"WF":{"iso":"WF","name":"Wallis and Futuna","visited":false},
	"EH":{"iso":"EH","name":"Western Sahara","visited":false},
	"YE":{"iso":"YE","name":"Yemen","visited":false},
	"ZM":{"iso":"ZM","name":"Zambia","visited":false},
	"ZW":{"iso":"ZW","name":"Zimbabwe","visited":false},
	"AX":{"iso":"AX","name":"Åland Islands","visited":false}
}';

$list = json_decode($list);
