<?php

$traveler_evidences = array(
	"When your backpack is less than 8kg",
	"Most of your jewlery is made of twine",
	"A 6 hours journey by bus is short!",
	"You rewear all of your clothes, including underwear, at least twice",
	"You know how to say hello and thank you in at least 15 languages",
	"The shoes you brought from home broke or were stolen months ago. Now you live in $2 flip flop -- which you consider expensive",
	"Your life fits in 6 plastic bags in your backpack",
	"You smoke, but every time you light up, you announce to anyone in ear shot that you really only smoke when you're traveling",
	"Spicy food is also a good way to clean your stomach",
	"You have intense cravings for Burger King...even though you're “mostly a vegetarian” back home",
	"Tuk-tuk and taxis say hello instead of “tuk-tuk sir?”",
	"You have at least five currencies in your wallet at any given time",
	"Your passport has a unlimited stay at any embassy but you can provide copies ;)",
	"You no longer really care about the answers to questions like, “Where are you from?” and, “How long are you traveling?” but ask them automatically.",
	"You no longer remember your address but your passport number",
	"You have no idea what day of the week it is, but you know how many days until your visa expires",
	"You can fix all your injuries with water and lipstick.",
	"You can name the national beer of choice from every place you've been",
	"If it was only you, you'd have 6 wives, 4 children, 5 houses and I'm counting only moms proposals for their daughters.",
	"Whenever you come across a roll of toilet paper, you take half with you",
	"Last time you bought soap and toothpaste was 6 month ago before a 10 days trek because you knew free accommodation doesn't provide any of them",
	"You are fluent in several languages: US (tank top), UK (vest), and Australian (singlet) English",
	"You no longer drink as hell because you like to wake up early and see the town waking up.",
	"You love airports. They have the best coffee and bathrooms! (Lexie, US girl)",
	"You already have a pre-thought answers to all questions and tricky technics from apparently friendly tuk-tuk, city guides and children.",
	"You have gotten great at goodbyes but still hate them",
	"Home currency isn't your reference anymore. You still think in phillipino pesos or lao kip.",
	"You've had amazing conversations using only pointing, miming and facial expressions",
	"When your friend don't want to believe your stories because Discovery Channel didn't mention this and ”man vs wild” looks like Winnie the pooh.",
	"Things like emergency exits and seat belts are no longer a priority.",
	"Chuck Norris asked you for directions",
	"Hostel discard piles are as good as H&amp;M",
	"An instant noodles soup is worth it!",
	"You begin at least two sentences a day with “When I was in… “ or “ My friend from… ” ",
	"You lust after fast internet (for uploading photos) and 3G has the best speed ever",
	"You can recite the safety speech of an air plane and you know the differences between the companies",
	"Your have never used the mosquito net you packed (Lexie)",
	"You never had mosquito net because mosquitos are your travel mates now... (Nico)",
	"You make lifelong friends with people you meet for a few hours",
	"When you stopped counting how many month you're travelling for",
	"You feel inappropriate in shorts that are just slightly above the knee",
	"Sleeping with a girl/guy is no longer an achievement but a good way to save money on accommodation",
	"You know how to order traditional dishes that aren't even on the menu",
	"Back home you know how to drive cars, asian motorbikes, western motorbikes, small buses, traditional boats of several countries, tuk-tuk, horse carts and you never worried about a licence.",
	"You have used plants and other homeopathic remedies because you know they'll be more effective than the local doctor",
	"You take planes like your previous boss takes the subway",
	"You get cold when it's 24 degrees celsius (you're American and use the celsius)",
	"$1 is expensive. ( <troll>You're French and you realise it's not even 1€ </troll>)",
	"You own one or more of the following: fake Ray Bans, hippie pants, cheap trekking shoes, local beer logo shirts, beaded bracelets",
	"You can use forks and spoons in a dozen ways according to the country you're thinking about",
	"Because 50 is nice but now you're here so... “Why not keep going?” ",
	"You realised long ago that there is a huge difference between longterm travel and vacation. Travel is a ton more work and much less glamorous, but you wouldn't trade it for the fanciest all-inclusive resort in the world.",
	"If you lost your pack, you could be totally comfortable with only your day pack",
	"You have a blog. Last update? Six months ago.",
	"Your Facebook news feed is dominated by people you met two weeks ago",
	"You can organise your tasks in two categories. Online, offline.",
	"You have photos of yourself scuba diving, rock climbing, trekking, and getting wasted",
	"A simple lace looks like a hundred features tool to you",
	"Gchat has been replaced by Facebook messenger and whatsapp",
	"You spent nights in the middle of nowhere but you know where is “nowhere”",
	"You know your a traveler when you miss hot showers and your family equally",
	"You didn't talk to your mom for weeks and she's fine with that",
	"You’re planning one trip while on another",
	"There are at least ten different songs that take you back to ten different places with a tear in your eye and a smile on your face.",
	"You have a collection of SIM cards from around the world and you keep all of them, just in case…",
	"You have an irrational love of flags",
	"You’re named after a city/country :p",
	"The local friend you met on the road suprises you by visiting you… on the road.",
	"You have no route but an expiration day on your visa",
	"Your friends go back home and say “I use drawers” and you use Google image to remind you how a drawer looks like!",
	"You know you're a traveler when you're back home for 4 days and you didn't get your backpack empty. 'Cause you know... we never know :p I even found myself putting back the toothbrush in the plastic bag this morning!",
);
